CREATE DATABASE CLIENTES
GO

USE CLIENTES
GO

CREATE SCHEMA VENTAS 
GO

CREATE SCHEMA TIPOS
GO

CREATE SCHEMA DATOS
GO

CREATE TABLE DATOS.CLIENTES(
	ID_CLIENTE INT PRIMARY KEY,
	NOMBRE nvarchar(30),
	APELLIDO_PATERNO nvarchar(15),
	APELLIDO_MATERNO nvarchar(15)
)
GO

CREATE TABLE DATOS.EDAD(
	FECHA_NACIMIENTO DATE,
	EDAD INT,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE) REFERENCES DATOS.CLIENTES(ID_CLIENTE)
)
GO

CREATE TABLE TIPOS.CLIENTES(
	ID_TIPOS INT PRIMARY KEY NOT NULL,
	GRUPO_CLIENTES VARCHAR(5)
)
GO

CREATE TABLE VENTAS.ALTA_CLIENTES(
	DIRECCION NVARCHAR(60),
	CODIGO_POSTAL VARCHAR(4),
	TELEFONO VARCHAR (8),
	CORREO_ELECTRONICO NVARCHAR(50),
	FECHA_ALTA DATE,
	ID_CLIENTE INT,
	ID_TIPOS INT,
	FOREIGN KEY (ID_CLIENTE) REFERENCES DATOS.CLIENTES(ID_CLIENTE),
	FOREIGN KEY (ID_TIPOS) REFERENCES TIPOS.CLIENTES(ID_TIPOS)
)
GO

BULK INSERT DATOS.CLIENTES
FROM 'D:\DATOS_CLIENTES.csv'
WITH (
		FORMAT = 'csv',
		FIELDTERMINATOR = ';',
		FIRSTROW = 2
)
GO

BULK INSERT DATOS.EDAD
FROM 'D:\DATOS_EDAD.csv'
WITH (
		FORMAT = 'csv',
		FIELDTERMINATOR = ';',
		FIRSTROW = 2
)
GO

BULK INSERT TIPOS.CLIENTES
FROM 'D:\TIPOS_CLIENTES.csv'
WITH (
		FORMAT = 'csv',
		FIELDTERMINATOR = ';',
		FIRSTROW = 2
)
GO

BULK INSERT VENTAS.ALTA_CLIENTES
FROM 'D:\ALTA_CLIENTES.csv'
WITH (
		FORMAT = 'csv',
		FIELDTERMINATOR = ';',
		FIRSTROW = 2
)
GO





